/**
 * Comprehensive gym exercise database.
 * 100+ exercises with categories, equipment, muscles, difficulty, and instructions.
 */

export type ExerciseCategory =
  | 'chest'
  | 'back'
  | 'shoulders'
  | 'legs'
  | 'biceps'
  | 'triceps'
  | 'core'
  | 'cardio'
  | 'full_body'

export type EquipmentType =
  | 'barbell'
  | 'dumbbell'
  | 'cable'
  | 'machine'
  | 'bodyweight'
  | 'kettlebell'
  | 'band'
  | 'other'

export type Difficulty = 'beginner' | 'intermediate' | 'advanced'

export interface GymExercise {
  id: string
  name: string
  category: ExerciseCategory
  equipment: EquipmentType
  primaryMuscles: string[]
  secondaryMuscles: string[]
  instructions: string
  difficulty: Difficulty
  defaultSets: number
  defaultReps: string
  defaultRest: number
}

/* ------------------------------------------------------------------ */
/*  Category metadata (colors, icons, labels)                         */
/* ------------------------------------------------------------------ */

export const CATEGORY_META: Record<
  ExerciseCategory,
  { label: string; color: string; bg: string }
> = {
  chest: { label: 'Chest', color: '#EF4444', bg: 'rgba(239,68,68,0.12)' },
  back: { label: 'Back', color: '#3B82F6', bg: 'rgba(59,130,246,0.12)' },
  shoulders: { label: 'Shoulders', color: '#F59E0B', bg: 'rgba(245,158,11,0.12)' },
  legs: { label: 'Legs', color: '#10B981', bg: 'rgba(16,185,129,0.12)' },
  biceps: { label: 'Biceps', color: '#8B5CF6', bg: 'rgba(139,92,246,0.12)' },
  triceps: { label: 'Triceps', color: '#EC4899', bg: 'rgba(236,72,153,0.12)' },
  core: { label: 'Core', color: '#06B6D4', bg: 'rgba(6,182,212,0.12)' },
  cardio: { label: 'Cardio', color: '#F97316', bg: 'rgba(249,115,22,0.12)' },
  full_body: { label: 'Full Body', color: '#6366F1', bg: 'rgba(99,102,241,0.12)' },
}

export const EQUIPMENT_META: Record<EquipmentType, { label: string }> = {
  barbell: { label: 'Barbell' },
  dumbbell: { label: 'Dumbbell' },
  cable: { label: 'Cable' },
  machine: { label: 'Machine' },
  bodyweight: { label: 'Bodyweight' },
  kettlebell: { label: 'Kettlebell' },
  band: { label: 'Band' },
  other: { label: 'Other' },
}

/* ------------------------------------------------------------------ */
/*  Exercise Database                                                 */
/* ------------------------------------------------------------------ */

export const EXERCISES: GymExercise[] = [
  // ═══════════════════════════════════════════════════════════════════
  //  CHEST
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    category: 'chest',
    equipment: 'barbell',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Triceps', 'Front Delts'],
    instructions: 'Lie on a flat bench, grip the bar slightly wider than shoulder-width. Lower to mid-chest, press back up.',
    difficulty: 'intermediate',
    defaultSets: 4,
    defaultReps: '8-10',
    defaultRest: 120,
  },
  {
    id: 'incline-barbell-bench',
    name: 'Incline Barbell Bench Press',
    category: 'chest',
    equipment: 'barbell',
    primaryMuscles: ['Upper Chest'],
    secondaryMuscles: ['Triceps', 'Front Delts'],
    instructions: 'Set bench to 30-45 degrees. Lower bar to upper chest, press up.',
    difficulty: 'intermediate',
    defaultSets: 4,
    defaultReps: '8-10',
    defaultRest: 120,
  },
  {
    id: 'decline-barbell-bench',
    name: 'Decline Barbell Bench Press',
    category: 'chest',
    equipment: 'barbell',
    primaryMuscles: ['Lower Chest'],
    secondaryMuscles: ['Triceps', 'Front Delts'],
    instructions: 'Set bench to a decline. Lower bar to lower chest, press up.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '8-10',
    defaultRest: 120,
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    category: 'chest',
    equipment: 'dumbbell',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Triceps', 'Front Delts'],
    instructions: 'Lie flat, press dumbbells from chest level up. Greater range of motion than barbell.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 90,
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    category: 'chest',
    equipment: 'dumbbell',
    primaryMuscles: ['Upper Chest'],
    secondaryMuscles: ['Triceps', 'Front Delts'],
    instructions: 'Set bench to 30-45 degrees. Press dumbbells from chest level up.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 90,
  },
  {
    id: 'dumbbell-flyes',
    name: 'Dumbbell Flyes',
    category: 'chest',
    equipment: 'dumbbell',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Front Delts'],
    instructions: 'Lie flat, arms extended. Lower dumbbells in an arc to sides, squeeze chest to return.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 60,
  },
  {
    id: 'cable-crossovers',
    name: 'Cable Crossovers',
    category: 'chest',
    equipment: 'cable',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Front Delts'],
    instructions: 'Set pulleys high, step forward. Bring handles together in front with slight bend in elbows.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 60,
  },
  {
    id: 'machine-chest-press',
    name: 'Machine Chest Press',
    category: 'chest',
    equipment: 'machine',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Triceps', 'Front Delts'],
    instructions: 'Sit with back against pad, grip handles at chest height. Press forward and return slowly.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 60,
  },
  {
    id: 'push-ups',
    name: 'Push-Ups',
    category: 'chest',
    equipment: 'bodyweight',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Triceps', 'Front Delts', 'Core'],
    instructions: 'Hands shoulder-width, body straight. Lower chest to ground, push back up.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '15-20',
    defaultRest: 60,
  },
  {
    id: 'chest-dips',
    name: 'Chest Dips',
    category: 'chest',
    equipment: 'bodyweight',
    primaryMuscles: ['Lower Chest'],
    secondaryMuscles: ['Triceps', 'Front Delts'],
    instructions: 'On parallel bars, lean forward slightly. Lower until upper arms are parallel to ground, push up.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRest: 90,
  },
  {
    id: 'pec-deck',
    name: 'Pec Deck Machine',
    category: 'chest',
    equipment: 'machine',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Front Delts'],
    instructions: 'Sit with back against pad, bring padded arms together in front. Squeeze chest at peak.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 60,
  },

  // ═══════════════════════════════════════════════════════════════════
  //  BACK
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    category: 'back',
    equipment: 'barbell',
    primaryMuscles: ['Lats', 'Rhomboids'],
    secondaryMuscles: ['Biceps', 'Rear Delts'],
    instructions: 'Hinge forward at hips, pull bar to lower chest. Squeeze shoulder blades together.',
    difficulty: 'intermediate',
    defaultSets: 4,
    defaultReps: '8-10',
    defaultRest: 120,
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    category: 'back',
    equipment: 'dumbbell',
    primaryMuscles: ['Lats', 'Rhomboids'],
    secondaryMuscles: ['Biceps', 'Rear Delts'],
    instructions: 'One hand and knee on bench, pull dumbbell to hip. Keep back flat.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 90,
  },
  {
    id: 'pull-ups',
    name: 'Pull-Ups',
    category: 'back',
    equipment: 'bodyweight',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps', 'Rhomboids'],
    instructions: 'Hang from bar with overhand grip. Pull chin over bar, lower with control.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '6-10',
    defaultRest: 120,
  },
  {
    id: 'chin-ups',
    name: 'Chin-Ups',
    category: 'back',
    equipment: 'bodyweight',
    primaryMuscles: ['Lats', 'Biceps'],
    secondaryMuscles: ['Rhomboids'],
    instructions: 'Hang from bar with underhand grip. Pull chin over bar, lower with control.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '6-10',
    defaultRest: 120,
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps', 'Rhomboids'],
    instructions: 'Sit at machine, pull bar to upper chest with wide grip. Lean back slightly.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 90,
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['Rhomboids', 'Mid Back'],
    secondaryMuscles: ['Biceps', 'Lats'],
    instructions: 'Sit with feet on platform, pull handle to abdomen. Squeeze shoulder blades.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 90,
  },
  {
    id: 't-bar-row',
    name: 'T-Bar Row',
    category: 'back',
    equipment: 'barbell',
    primaryMuscles: ['Mid Back', 'Lats'],
    secondaryMuscles: ['Biceps', 'Rear Delts'],
    instructions: 'Straddle the bar, use V-handle. Pull to chest, squeeze back.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '8-10',
    defaultRest: 90,
  },
  {
    id: 'face-pulls',
    name: 'Face Pulls',
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['Rear Delts', 'Rhomboids'],
    secondaryMuscles: ['Rotator Cuff'],
    instructions: 'Set cable at face height with rope. Pull toward face, externally rotate at end.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '15-20',
    defaultRest: 60,
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    category: 'back',
    equipment: 'barbell',
    primaryMuscles: ['Lower Back', 'Glutes', 'Hamstrings'],
    secondaryMuscles: ['Traps', 'Quads', 'Core'],
    instructions: 'Stand with feet hip-width, grip bar. Drive through heels, extend hips and knees together.',
    difficulty: 'advanced',
    defaultSets: 4,
    defaultReps: '5',
    defaultRest: 180,
  },
  {
    id: 'hyperextensions',
    name: 'Hyperextensions',
    category: 'back',
    equipment: 'bodyweight',
    primaryMuscles: ['Lower Back'],
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    instructions: 'On hyperextension bench, lower upper body. Extend back up to straight position.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 60,
  },
  {
    id: 'machine-row',
    name: 'Machine Row',
    category: 'back',
    equipment: 'machine',
    primaryMuscles: ['Lats', 'Rhomboids'],
    secondaryMuscles: ['Biceps'],
    instructions: 'Sit at machine with chest against pad. Pull handles back, squeeze shoulder blades.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 60,
  },
  {
    id: 'single-arm-cable-row',
    name: 'Single Arm Cable Row',
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['Lats', 'Rhomboids'],
    secondaryMuscles: ['Biceps', 'Core'],
    instructions: 'Stand at cable machine, pull handle to hip one arm at a time. Anti-rotation challenge.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 60,
  },

  // ═══════════════════════════════════════════════════════════════════
  //  SHOULDERS
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    category: 'shoulders',
    equipment: 'barbell',
    primaryMuscles: ['Front Delts', 'Mid Delts'],
    secondaryMuscles: ['Triceps', 'Core'],
    instructions: 'Stand with bar at shoulder height. Press straight overhead, lock out arms.',
    difficulty: 'intermediate',
    defaultSets: 4,
    defaultReps: '6-8',
    defaultRest: 120,
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['Front Delts', 'Mid Delts'],
    secondaryMuscles: ['Triceps'],
    instructions: 'Sit or stand, press dumbbells from shoulder level overhead.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '8-10',
    defaultRest: 90,
  },
  {
    id: 'lateral-raises',
    name: 'Lateral Raises',
    category: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['Mid Delts'],
    secondaryMuscles: ['Traps'],
    instructions: 'Stand with dumbbells at sides. Raise arms out to sides until parallel with floor.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 60,
  },
  {
    id: 'front-raises',
    name: 'Front Raises',
    category: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['Front Delts'],
    secondaryMuscles: ['Mid Delts'],
    instructions: 'Stand with dumbbells in front of thighs. Raise arms forward to shoulder height.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 60,
  },
  {
    id: 'reverse-flyes',
    name: 'Reverse Flyes',
    category: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['Rear Delts'],
    secondaryMuscles: ['Rhomboids'],
    instructions: 'Bend forward at hips, raise dumbbells out to sides with slight elbow bend.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 60,
  },
  {
    id: 'arnold-press',
    name: 'Arnold Press',
    category: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['Front Delts', 'Mid Delts'],
    secondaryMuscles: ['Triceps'],
    instructions: 'Start with palms facing you. Press up while rotating palms to face forward at top.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '8-10',
    defaultRest: 90,
  },
  {
    id: 'upright-rows',
    name: 'Upright Rows',
    category: 'shoulders',
    equipment: 'barbell',
    primaryMuscles: ['Mid Delts', 'Traps'],
    secondaryMuscles: ['Biceps'],
    instructions: 'Hold bar with narrow grip. Pull up along body to chin level, elbows high.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 60,
  },
  {
    id: 'cable-lateral-raises',
    name: 'Cable Lateral Raises',
    category: 'shoulders',
    equipment: 'cable',
    primaryMuscles: ['Mid Delts'],
    secondaryMuscles: ['Traps'],
    instructions: 'Stand beside low cable, raise arm out to side. Constant tension throughout.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 60,
  },
  {
    id: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    category: 'shoulders',
    equipment: 'machine',
    primaryMuscles: ['Front Delts', 'Mid Delts'],
    secondaryMuscles: ['Triceps'],
    instructions: 'Sit at machine, press handles overhead. Good for beginners or heavy training.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 90,
  },
  {
    id: 'barbell-shrugs',
    name: 'Barbell Shrugs',
    category: 'shoulders',
    equipment: 'barbell',
    primaryMuscles: ['Traps'],
    secondaryMuscles: ['Neck'],
    instructions: 'Hold bar at waist, shrug shoulders straight up toward ears. Hold at top.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 60,
  },
  {
    id: 'dumbbell-shrugs',
    name: 'Dumbbell Shrugs',
    category: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['Traps'],
    secondaryMuscles: ['Neck'],
    instructions: 'Hold dumbbells at sides, shrug shoulders up toward ears. Hold at top.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 60,
  },

  // ═══════════════════════════════════════════════════════════════════
  //  LEGS
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'barbell-squat',
    name: 'Barbell Squat',
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['Quads', 'Glutes'],
    secondaryMuscles: ['Hamstrings', 'Core', 'Lower Back'],
    instructions: 'Bar on upper back, feet shoulder-width. Squat to parallel or below, drive up.',
    difficulty: 'intermediate',
    defaultSets: 4,
    defaultReps: '6-8',
    defaultRest: 150,
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes', 'Core'],
    instructions: 'Bar on front delts, elbows high. Squat deep, keep torso upright.',
    difficulty: 'advanced',
    defaultSets: 4,
    defaultReps: '6-8',
    defaultRest: 150,
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Quads', 'Glutes'],
    secondaryMuscles: ['Hamstrings'],
    instructions: 'Sit in machine, feet shoulder-width on platform. Press away, don\'t lock knees.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 90,
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['Hamstrings', 'Glutes'],
    secondaryMuscles: ['Lower Back'],
    instructions: 'Hold bar, hinge at hips with slight knee bend. Lower until hamstring stretch, drive hips forward.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '8-10',
    defaultRest: 120,
  },
  {
    id: 'leg-extensions',
    name: 'Leg Extensions',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Quads'],
    secondaryMuscles: [],
    instructions: 'Sit at machine, extend legs straight. Squeeze quads at top, lower slowly.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 60,
  },
  {
    id: 'leg-curls',
    name: 'Leg Curls',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: [],
    instructions: 'Lie face down, curl pad toward glutes. Squeeze hamstrings, lower slowly.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 60,
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'legs',
    equipment: 'dumbbell',
    primaryMuscles: ['Quads', 'Glutes'],
    secondaryMuscles: ['Hamstrings', 'Core'],
    instructions: 'Rear foot on bench, lower front knee to 90 degrees. Drive through front heel.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 90,
  },
  {
    id: 'walking-lunges',
    name: 'Walking Lunges',
    category: 'legs',
    equipment: 'dumbbell',
    primaryMuscles: ['Quads', 'Glutes'],
    secondaryMuscles: ['Hamstrings', 'Core'],
    instructions: 'Step forward into a lunge, alternating legs. Keep torso upright.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12 each',
    defaultRest: 90,
  },
  {
    id: 'standing-calf-raises',
    name: 'Standing Calf Raises',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Calves'],
    secondaryMuscles: [],
    instructions: 'Stand on calf raise machine, rise up on toes. Full stretch at bottom.',
    difficulty: 'beginner',
    defaultSets: 4,
    defaultReps: '12-15',
    defaultRest: 60,
  },
  {
    id: 'seated-calf-raises',
    name: 'Seated Calf Raises',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Calves'],
    secondaryMuscles: [],
    instructions: 'Sit at calf machine, raise heels up. Targets the soleus muscle.',
    difficulty: 'beginner',
    defaultSets: 4,
    defaultReps: '15-20',
    defaultRest: 60,
  },
  {
    id: 'hack-squat',
    name: 'Hack Squat',
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    instructions: 'Back against pad, feet shoulder-width. Squat down, press up through heels.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '8-10',
    defaultRest: 90,
  },
  {
    id: 'hip-thrusts',
    name: 'Hip Thrusts',
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Hamstrings'],
    instructions: 'Upper back on bench, bar over hips. Drive hips up, squeeze glutes at top.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 90,
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    category: 'legs',
    equipment: 'dumbbell',
    primaryMuscles: ['Quads', 'Glutes'],
    secondaryMuscles: ['Core'],
    instructions: 'Hold dumbbell at chest, squat deep. Great for learning squat form.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 90,
  },
  {
    id: 'sumo-deadlift',
    name: 'Sumo Deadlift',
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['Glutes', 'Quads', 'Hamstrings'],
    secondaryMuscles: ['Lower Back', 'Adductors'],
    instructions: 'Wide stance, grip bar between legs. Push floor apart while driving hips forward.',
    difficulty: 'advanced',
    defaultSets: 4,
    defaultReps: '5-6',
    defaultRest: 180,
  },
  {
    id: 'step-ups',
    name: 'Step-Ups',
    category: 'legs',
    equipment: 'dumbbell',
    primaryMuscles: ['Quads', 'Glutes'],
    secondaryMuscles: ['Hamstrings'],
    instructions: 'Step onto box or bench with one foot, drive up to standing. Alternate legs.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10 each',
    defaultRest: 60,
  },

  // ═══════════════════════════════════════════════════════════════════
  //  BICEPS
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'barbell-curls',
    name: 'Barbell Curls',
    category: 'biceps',
    equipment: 'barbell',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Forearms'],
    instructions: 'Stand with bar, curl up keeping elbows pinned to sides. Lower with control.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 60,
  },
  {
    id: 'dumbbell-curls',
    name: 'Dumbbell Curls',
    category: 'biceps',
    equipment: 'dumbbell',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Forearms'],
    instructions: 'Curl dumbbells alternating or together. Full range of motion, squeeze at top.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 60,
  },
  {
    id: 'hammer-curls',
    name: 'Hammer Curls',
    category: 'biceps',
    equipment: 'dumbbell',
    primaryMuscles: ['Biceps', 'Brachialis'],
    secondaryMuscles: ['Forearms'],
    instructions: 'Curl with palms facing each other (neutral grip). Targets brachialis.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 60,
  },
  {
    id: 'preacher-curls',
    name: 'Preacher Curls',
    category: 'biceps',
    equipment: 'barbell',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: [],
    instructions: 'Arms on preacher bench, curl bar up. Isolates biceps, no momentum.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 60,
  },
  {
    id: 'cable-curls',
    name: 'Cable Curls',
    category: 'biceps',
    equipment: 'cable',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Forearms'],
    instructions: 'Stand at low cable, curl bar up. Constant tension throughout range.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 60,
  },
  {
    id: 'concentration-curls',
    name: 'Concentration Curls',
    category: 'biceps',
    equipment: 'dumbbell',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: [],
    instructions: 'Sit with elbow against inner thigh. Curl dumbbell up, squeeze at top.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 60,
  },
  {
    id: 'ez-bar-curls',
    name: 'EZ Bar Curls',
    category: 'biceps',
    equipment: 'barbell',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Forearms'],
    instructions: 'Use EZ curl bar for wrist-friendly grip. Curl up with controlled motion.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 60,
  },
  {
    id: 'incline-dumbbell-curls',
    name: 'Incline Dumbbell Curls',
    category: 'biceps',
    equipment: 'dumbbell',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: [],
    instructions: 'Sit on incline bench, arms hanging. Curl up for stretched starting position.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 60,
  },
  {
    id: 'spider-curls',
    name: 'Spider Curls',
    category: 'biceps',
    equipment: 'dumbbell',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: [],
    instructions: 'Lean chest on incline bench, curl dumbbells. Peak contraction focus.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 60,
  },

  // ═══════════════════════════════════════════════════════════════════
  //  TRICEPS
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'tricep-pushdowns',
    name: 'Tricep Pushdowns',
    category: 'triceps',
    equipment: 'cable',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: [],
    instructions: 'At cable machine, push bar or rope down. Keep elbows pinned, extend fully.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 60,
  },
  {
    id: 'skull-crushers',
    name: 'Skull Crushers',
    category: 'triceps',
    equipment: 'barbell',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: [],
    instructions: 'Lie on bench, lower bar to forehead. Extend arms back up. Use EZ bar if available.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 90,
  },
  {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    category: 'triceps',
    equipment: 'dumbbell',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: [],
    instructions: 'Hold dumbbell overhead with both hands. Lower behind head, extend up.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 60,
  },
  {
    id: 'close-grip-bench-press',
    name: 'Close-Grip Bench Press',
    category: 'triceps',
    equipment: 'barbell',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: ['Chest', 'Front Delts'],
    instructions: 'Bench press with hands shoulder-width or narrower. Emphasizes triceps.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '8-10',
    defaultRest: 90,
  },
  {
    id: 'tricep-dips',
    name: 'Tricep Dips',
    category: 'triceps',
    equipment: 'bodyweight',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: ['Chest', 'Front Delts'],
    instructions: 'On parallel bars or bench, keep torso upright. Lower and press up.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRest: 90,
  },
  {
    id: 'cable-overhead-extension',
    name: 'Cable Overhead Extension',
    category: 'triceps',
    equipment: 'cable',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: [],
    instructions: 'Face away from cable, extend rope overhead. Great stretch and contraction.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 60,
  },
  {
    id: 'diamond-push-ups',
    name: 'Diamond Push-Ups',
    category: 'triceps',
    equipment: 'bodyweight',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: ['Chest'],
    instructions: 'Hands together forming diamond shape. Push-up focusing on tricep engagement.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '10-15',
    defaultRest: 60,
  },
  {
    id: 'tricep-kickbacks',
    name: 'Tricep Kickbacks',
    category: 'triceps',
    equipment: 'dumbbell',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: [],
    instructions: 'Bend forward, upper arm parallel to floor. Extend forearm back, squeeze.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 60,
  },

  // ═══════════════════════════════════════════════════════════════════
  //  CORE
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'plank',
    name: 'Plank',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Core', 'Abs'],
    secondaryMuscles: ['Shoulders', 'Lower Back'],
    instructions: 'Forearms and toes on ground, body straight. Hold position.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '30-60 sec',
    defaultRest: 60,
  },
  {
    id: 'crunches',
    name: 'Crunches',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Upper Abs'],
    secondaryMuscles: [],
    instructions: 'Lie on back, knees bent. Curl upper body toward knees, squeeze abs.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '15-20',
    defaultRest: 45,
  },
  {
    id: 'russian-twists',
    name: 'Russian Twists',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Obliques'],
    secondaryMuscles: ['Abs'],
    instructions: 'Sit with feet off ground, lean back slightly. Twist torso side to side.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '20 total',
    defaultRest: 45,
  },
  {
    id: 'leg-raises',
    name: 'Leg Raises',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Lower Abs'],
    secondaryMuscles: ['Hip Flexors'],
    instructions: 'Lie flat, raise legs to vertical. Lower slowly without touching floor.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 45,
  },
  {
    id: 'cable-woodchops',
    name: 'Cable Woodchops',
    category: 'core',
    equipment: 'cable',
    primaryMuscles: ['Obliques', 'Core'],
    secondaryMuscles: ['Shoulders'],
    instructions: 'Set cable high, pull diagonally down across body. Rotate through core.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '12 each',
    defaultRest: 60,
  },
  {
    id: 'ab-wheel-rollouts',
    name: 'Ab Wheel Rollouts',
    category: 'core',
    equipment: 'other',
    primaryMuscles: ['Abs', 'Core'],
    secondaryMuscles: ['Lats', 'Shoulders'],
    instructions: 'Kneel with ab wheel. Roll forward extending body, pull back with abs.',
    difficulty: 'advanced',
    defaultSets: 3,
    defaultReps: '8-12',
    defaultRest: 60,
  },
  {
    id: 'dead-bugs',
    name: 'Dead Bugs',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Core', 'Abs'],
    secondaryMuscles: ['Hip Flexors'],
    instructions: 'Lie on back, arms up. Extend opposite arm and leg alternately. Keep back flat.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '12 each',
    defaultRest: 45,
  },
  {
    id: 'mountain-climbers',
    name: 'Mountain Climbers',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Core', 'Abs'],
    secondaryMuscles: ['Hip Flexors', 'Shoulders'],
    instructions: 'Push-up position, drive knees to chest alternately at rapid pace.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '30 sec',
    defaultRest: 45,
  },
  {
    id: 'hanging-leg-raises',
    name: 'Hanging Leg Raises',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Lower Abs'],
    secondaryMuscles: ['Hip Flexors', 'Grip'],
    instructions: 'Hang from bar, raise legs to horizontal or higher. Lower with control.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '10-12',
    defaultRest: 60,
  },
  {
    id: 'bicycle-crunches',
    name: 'Bicycle Crunches',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Abs', 'Obliques'],
    secondaryMuscles: [],
    instructions: 'Lie on back, bring opposite elbow to knee in pedaling motion.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '20 total',
    defaultRest: 45,
  },
  {
    id: 'cable-crunches',
    name: 'Cable Crunches',
    category: 'core',
    equipment: 'cable',
    primaryMuscles: ['Abs'],
    secondaryMuscles: [],
    instructions: 'Kneel at high cable, crunch down bringing elbows to knees. Weighted ab work.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '12-15',
    defaultRest: 60,
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['Obliques'],
    secondaryMuscles: ['Core', 'Shoulders'],
    instructions: 'Lie on side, support on forearm. Hold body in straight line.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '30 sec each',
    defaultRest: 45,
  },

  // ═══════════════════════════════════════════════════════════════════
  //  CARDIO
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'treadmill-running',
    name: 'Treadmill Running',
    category: 'cardio',
    equipment: 'machine',
    primaryMuscles: ['Quads', 'Hamstrings', 'Calves'],
    secondaryMuscles: ['Core', 'Glutes'],
    instructions: 'Run at steady pace on treadmill. Adjust speed and incline to goal.',
    difficulty: 'beginner',
    defaultSets: 1,
    defaultReps: '20-30 min',
    defaultRest: 0,
  },
  {
    id: 'cycling',
    name: 'Stationary Cycling',
    category: 'cardio',
    equipment: 'machine',
    primaryMuscles: ['Quads', 'Hamstrings'],
    secondaryMuscles: ['Calves', 'Glutes'],
    instructions: 'Cycle at moderate to high resistance. Great for low-impact cardio.',
    difficulty: 'beginner',
    defaultSets: 1,
    defaultReps: '20-30 min',
    defaultRest: 0,
  },
  {
    id: 'rowing-machine',
    name: 'Rowing Machine',
    category: 'cardio',
    equipment: 'machine',
    primaryMuscles: ['Back', 'Legs'],
    secondaryMuscles: ['Biceps', 'Core', 'Shoulders'],
    instructions: 'Push with legs first, then pull with back and arms. Full body cardio.',
    difficulty: 'beginner',
    defaultSets: 1,
    defaultReps: '15-20 min',
    defaultRest: 0,
  },
  {
    id: 'stair-climber',
    name: 'Stair Climber',
    category: 'cardio',
    equipment: 'machine',
    primaryMuscles: ['Quads', 'Glutes', 'Calves'],
    secondaryMuscles: ['Hamstrings'],
    instructions: 'Step steadily, maintain upright posture. Don\'t lean on handles.',
    difficulty: 'beginner',
    defaultSets: 1,
    defaultReps: '15-20 min',
    defaultRest: 0,
  },
  {
    id: 'elliptical',
    name: 'Elliptical',
    category: 'cardio',
    equipment: 'machine',
    primaryMuscles: ['Quads', 'Glutes'],
    secondaryMuscles: ['Hamstrings', 'Core'],
    instructions: 'Low-impact full body movement. Adjust resistance for intensity.',
    difficulty: 'beginner',
    defaultSets: 1,
    defaultReps: '20-30 min',
    defaultRest: 0,
  },
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    category: 'cardio',
    equipment: 'other',
    primaryMuscles: ['Calves'],
    secondaryMuscles: ['Shoulders', 'Core', 'Quads'],
    instructions: 'Jump with both feet, spin rope with wrists. Great for conditioning.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '2 min',
    defaultRest: 60,
  },
  {
    id: 'battle-ropes',
    name: 'Battle Ropes',
    category: 'cardio',
    equipment: 'other',
    primaryMuscles: ['Shoulders', 'Arms'],
    secondaryMuscles: ['Core', 'Back'],
    instructions: 'Alternate arms creating waves in ropes. High intensity conditioning.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '30 sec',
    defaultRest: 60,
  },
  {
    id: 'box-jumps',
    name: 'Box Jumps',
    category: 'cardio',
    equipment: 'other',
    primaryMuscles: ['Quads', 'Glutes', 'Calves'],
    secondaryMuscles: ['Core'],
    instructions: 'Jump onto box from standing position. Step down, repeat.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '8-10',
    defaultRest: 90,
  },

  // ═══════════════════════════════════════════════════════════════════
  //  FULL BODY
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'clean-and-press',
    name: 'Clean and Press',
    category: 'full_body',
    equipment: 'barbell',
    primaryMuscles: ['Shoulders', 'Legs', 'Back'],
    secondaryMuscles: ['Core', 'Triceps', 'Traps'],
    instructions: 'Clean bar from floor to shoulders, then press overhead. Olympic lift variation.',
    difficulty: 'advanced',
    defaultSets: 3,
    defaultReps: '5-6',
    defaultRest: 120,
  },
  {
    id: 'kettlebell-swings',
    name: 'Kettlebell Swings',
    category: 'full_body',
    equipment: 'kettlebell',
    primaryMuscles: ['Glutes', 'Hamstrings'],
    secondaryMuscles: ['Core', 'Shoulders', 'Back'],
    instructions: 'Hinge at hips, swing kettlebell to chest height. Power from hips, not arms.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '15-20',
    defaultRest: 60,
  },
  {
    id: 'burpees',
    name: 'Burpees',
    category: 'full_body',
    equipment: 'bodyweight',
    primaryMuscles: ['Full Body'],
    secondaryMuscles: ['Core', 'Chest', 'Legs'],
    instructions: 'Squat, jump to push-up, push-up, jump back to squat, jump up. Repeat.',
    difficulty: 'intermediate',
    defaultSets: 3,
    defaultReps: '10-15',
    defaultRest: 60,
  },
  {
    id: 'thrusters',
    name: 'Thrusters',
    category: 'full_body',
    equipment: 'barbell',
    primaryMuscles: ['Quads', 'Shoulders'],
    secondaryMuscles: ['Glutes', 'Core', 'Triceps'],
    instructions: 'Front squat into overhead press in one fluid motion. Demanding full-body exercise.',
    difficulty: 'advanced',
    defaultSets: 3,
    defaultReps: '8-10',
    defaultRest: 120,
  },
  {
    id: 'turkish-get-up',
    name: 'Turkish Get-Up',
    category: 'full_body',
    equipment: 'kettlebell',
    primaryMuscles: ['Core', 'Shoulders'],
    secondaryMuscles: ['Glutes', 'Legs', 'Back'],
    instructions: 'Lie down with weight overhead. Stand up while keeping weight above you. Complex movement.',
    difficulty: 'advanced',
    defaultSets: 3,
    defaultReps: '3 each',
    defaultRest: 90,
  },
  {
    id: 'farmers-walk',
    name: 'Farmer\'s Walk',
    category: 'full_body',
    equipment: 'dumbbell',
    primaryMuscles: ['Grip', 'Traps', 'Core'],
    secondaryMuscles: ['Legs', 'Shoulders'],
    instructions: 'Hold heavy dumbbells at sides, walk for distance or time. Keep posture upright.',
    difficulty: 'beginner',
    defaultSets: 3,
    defaultReps: '40 meters',
    defaultRest: 90,
  },
  {
    id: 'man-makers',
    name: 'Man Makers',
    category: 'full_body',
    equipment: 'dumbbell',
    primaryMuscles: ['Full Body'],
    secondaryMuscles: ['Core', 'Shoulders', 'Back', 'Chest'],
    instructions: 'Push-up, row each side, jump to squat, clean to overhead press. Ultimate combo.',
    difficulty: 'advanced',
    defaultSets: 3,
    defaultReps: '6-8',
    defaultRest: 120,
  },
  {
    id: 'power-clean',
    name: 'Power Clean',
    category: 'full_body',
    equipment: 'barbell',
    primaryMuscles: ['Back', 'Legs', 'Traps'],
    secondaryMuscles: ['Core', 'Shoulders'],
    instructions: 'Explosive pull from floor, catch bar at shoulders. Olympic lift for power.',
    difficulty: 'advanced',
    defaultSets: 4,
    defaultReps: '3-5',
    defaultRest: 150,
  },
]

/* ------------------------------------------------------------------ */
/*  Helper functions                                                  */
/* ------------------------------------------------------------------ */

/** Get all unique categories present in the database */
export function getCategories(): ExerciseCategory[] {
  return Object.keys(CATEGORY_META) as ExerciseCategory[]
}

/** Get all unique equipment types present in the database */
export function getEquipmentTypes(): EquipmentType[] {
  return Object.keys(EQUIPMENT_META) as EquipmentType[]
}

/** Search exercises by name, category, equipment, or muscles */
export function searchExercises(
  query: string,
  filters?: {
    category?: ExerciseCategory | null
    equipment?: EquipmentType | null
  }
): GymExercise[] {
  let results = EXERCISES

  if (filters?.category) {
    results = results.filter((e) => e.category === filters.category)
  }

  if (filters?.equipment) {
    results = results.filter((e) => e.equipment === filters.equipment)
  }

  if (query.trim()) {
    const q = query.toLowerCase().trim()
    results = results.filter(
      (e) =>
        e.name.toLowerCase().includes(q) ||
        e.category.toLowerCase().includes(q) ||
        e.primaryMuscles.some((m) => m.toLowerCase().includes(q)) ||
        e.secondaryMuscles.some((m) => m.toLowerCase().includes(q)) ||
        e.equipment.toLowerCase().includes(q)
    )
  }

  return results
}

/** Get exercises by category */
export function getExercisesByCategory(category: ExerciseCategory): GymExercise[] {
  return EXERCISES.filter((e) => e.category === category)
}

/** Find a specific exercise by ID */
export function getExerciseById(id: string): GymExercise | undefined {
  return EXERCISES.find((e) => e.id === id)
}
